import type { Metadata } from 'next';
import React from 'react';
import { Section, SectionHeading } from '@/components/marketing/Section';
import { generateSEO } from '@/lib/seo';

export const metadata: Metadata = generateSEO({
  title: 'DMCA Notice',
  description: 'Submit intellectual property infringement reports or copyright disputes to Nomen legal operations.',
  keywords: ['copyright agent', 'dmca notice', 'copyright dispute', 'nomen trademark contact'],
  path: '/dmca',
});

export default function DmcaPage() {
  return (
    <Section className="pt-32" narrow>
      <SectionHeading title="DMCA Copyright Notice" eyebrow="Legal" />
      <div className="prose text-slate-700 leading-relaxed space-y-6 pt-4">
        <p className="text-sm text-slate-400">Last updated: June 29, 2026</p>
        <p>
          Nomen, Inc. respects the intellectual property rights of others. In accordance with the Digital Millennium
          Copyright Act (DMCA), we have designated a copyright agent to handle reports of infringement.
        </p>

        <h2 className="text-xl font-bold text-slate-900 pt-4">1. Filing an Infringement Claim</h2>
        <p>
          If you believe that your copyrighted work is being hosting, parsed, or generated by our services in a way
          that constitutes copyright violation, please send a written notice to our designated agent containing:
        </p>
        <ul className="list-disc pl-6 space-y-2" role="list">
          <li>A physical or electronic signature of the authorized copyright owner.</li>
          <li>Identification of the copyrighted work claimed to have been infringed.</li>
          <li>Detailed description of where the infringing material is located on our platform (including specific URLs).</li>
          <li>Your contact details: address, phone number, and email address.</li>
          <li>A statement indicating your good-faith belief that the disputed use is not authorized.</li>
          <li>A statement made under penalty of perjury that the information in your report is accurate.</li>
        </ul>

        <h2 className="text-xl font-bold text-slate-900 pt-4">2. Designated Agent Address</h2>
        <p className="text-sm text-slate-600 bg-slate-50 p-4 border border-slate-200 rounded-lg">
          Nomen, Inc. Attn: Legal Operations / Copyright Agent<br />
          100 Pine Street, Suite 1250<br />
          San Francisco, CA 94111<br />
          Email: legal@nomen.ai
        </p>

        <h2 className="text-xl font-bold text-slate-900 pt-4">3. Counter-Notifications</h2>
        <p>
          If you believe your content was disabled by mistake or misidentification, you may submit a counter-notice
          to our agent. This must include your signature, identification of the disabled content, your contact info,
          and a statement consenting to federal court jurisdiction.
        </p>
      </div>
    </Section>
  );
}
