apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: nomen-api-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nomen-api
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 75
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: nomen-web-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nomen-web
  minReplicas: 2
  maxReplicas: 8
  targetCPUUtilizationPercentage: 80
